### ISSUE TITLE
Rework UI / add css

### ISSUE THREAD

**Issue by halamix2** [GramyPomagamy/GPST#4]
Let's just use Vuetify and be done with this

**Comment by herniezz** [comment]
Here's the link for mockup project in figma: [https://www.figma.com/design/MojveykVBlijmBcbsSM8OJ/GPST-remake?node-id=0-1&m=dev](url)

**Comment by halamix2** [comment]
I'll implement something similar to the figma mockup, 2-column layout that can collapse to 1 column on tiny screens (partially implemented in https://github.com/GramyPomagamy/GPST/commit/6d81eb679a891142deb240fe31238b14ffd69467): 
![obraz](https://github.com/user-attachments/assets/a1eb2172-d34c-41a1-827b-d686599e3bb0)
![obraz](https://github.com/user-attachments/assets/04c2def6-9853-4fb9-974c-47a9c2ce8eb7)

**Comment by halamix2** [comment]
UI should look way better now
