### ISSUE TITLE
Default zoom / textbox positions

### ISSUE THREAD

**Issue by florczakraf** [GramyPomagamy/GPST#62]
The website looks like it was made for 4k screens judging by how it looks on 1920x1080 (which will be the resolution that the volunteers will have on the event as well):

![image](https://github.com/user-attachments/assets/bdd9f894-336b-4f69-8eee-d8a4799db53b)

I'd suggest to make it more friendly for the most commonly used resolution. For example, we could move the text fields from the bottom to the side. That would *almost* eliminate the need for scrolling the page:

![image](https://github.com/user-attachments/assets/5a83db4a-0b25-4d8d-9f84-97ed3dd1f6d8)

**Comment by halamix2** [comment]
- Basically #2, I'll have to do this UI rework finally

**Comment by halamix2** [comment]
Closing in favor of #4
